//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketRestaurant
    {
        public long id { get; set; }
        public string Label { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> PercentageEnterprise { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
