//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrarySalary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_Transmitter
    {
        public BILL_Transmitter()
        {
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
        }
    
        public long Transmitter_Id { get; set; }
        public string CompanyName { get; set; }
        public string Adress { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string City { get; set; }
        public long NSiret { get; set; }
        public string AdressMail { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    }
}
