//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrarySalary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleModules = new HashSet<RoleModule>();
            this.Users = new HashSet<User>();
        }
    
        public long Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<RoleModule> RoleModules { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
