//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserControl_GestionClient.ClientServiceGestionClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation[] BILL_BillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.COMPTA_CustomerJournalLine[] COMPTA_CustomerJournalLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.COMPTA_SupplierJournalLine[] COMPTA_SupplierJournalLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] Company_ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int postalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string siretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation[] BILL_BillQuotation {
            get {
                return this.BILL_BillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationField, value) != true)) {
                    this.BILL_BillQuotationField = value;
                    this.RaisePropertyChanged("BILL_BillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.COMPTA_CustomerJournalLine[] COMPTA_CustomerJournalLine {
            get {
                return this.COMPTA_CustomerJournalLineField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPTA_CustomerJournalLineField, value) != true)) {
                    this.COMPTA_CustomerJournalLineField = value;
                    this.RaisePropertyChanged("COMPTA_CustomerJournalLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.COMPTA_SupplierJournalLine[] COMPTA_SupplierJournalLine {
            get {
                return this.COMPTA_SupplierJournalLineField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPTA_SupplierJournalLineField, value) != true)) {
                    this.COMPTA_SupplierJournalLineField = value;
                    this.RaisePropertyChanged("COMPTA_SupplierJournalLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] Company_Contact {
            get {
                return this.Company_ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.Company_ContactField, value) != true)) {
                    this.Company_ContactField = value;
                    this.RaisePropertyChanged("Company_Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int postalcode {
            get {
                return this.postalcodeField;
            }
            set {
                if ((this.postalcodeField.Equals(value) != true)) {
                    this.postalcodeField = value;
                    this.RaisePropertyChanged("postalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string siret {
            get {
                return this.siretField;
            }
            set {
                if ((object.ReferenceEquals(this.siretField, value) != true)) {
                    this.siretField = value;
                    this.RaisePropertyChanged("siret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_BillQuotation", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_BillQuotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotationStatus[] BILL_BillQuotationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_LineBillQuotation[] BILL_LineBillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Transmitter BILL_TransmitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillQuotation_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Company_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NBillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Transmitter_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountDF {
            get {
                return this.AmountDFField;
            }
            set {
                if ((this.AmountDFField.Equals(value) != true)) {
                    this.AmountDFField = value;
                    this.RaisePropertyChanged("AmountDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotationStatus[] BILL_BillQuotationStatus {
            get {
                return this.BILL_BillQuotationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationStatusField, value) != true)) {
                    this.BILL_BillQuotationStatusField = value;
                    this.RaisePropertyChanged("BILL_BillQuotationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_LineBillQuotation[] BILL_LineBillQuotation {
            get {
                return this.BILL_LineBillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_LineBillQuotationField, value) != true)) {
                    this.BILL_LineBillQuotationField = value;
                    this.RaisePropertyChanged("BILL_LineBillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Transmitter BILL_Transmitter {
            get {
                return this.BILL_TransmitterField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_TransmitterField, value) != true)) {
                    this.BILL_TransmitterField = value;
                    this.RaisePropertyChanged("BILL_Transmitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillQuotation_Id {
            get {
                return this.BillQuotation_IdField;
            }
            set {
                if ((this.BillQuotation_IdField.Equals(value) != true)) {
                    this.BillQuotation_IdField = value;
                    this.RaisePropertyChanged("BillQuotation_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Company_Id {
            get {
                return this.Company_IdField;
            }
            set {
                if ((this.Company_IdField.Equals(value) != true)) {
                    this.Company_IdField = value;
                    this.RaisePropertyChanged("Company_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBillQuotation {
            get {
                return this.DateBillQuotationField;
            }
            set {
                if ((this.DateBillQuotationField.Equals(value) != true)) {
                    this.DateBillQuotationField = value;
                    this.RaisePropertyChanged("DateBillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NBill {
            get {
                return this.NBillField;
            }
            set {
                if ((object.ReferenceEquals(this.NBillField, value) != true)) {
                    this.NBillField = value;
                    this.RaisePropertyChanged("NBill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Transmitter_Id {
            get {
                return this.Transmitter_IdField;
            }
            set {
                if ((this.Transmitter_IdField.Equals(value) != true)) {
                    this.Transmitter_IdField = value;
                    this.RaisePropertyChanged("Transmitter_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vat {
            get {
                return this.VatField;
            }
            set {
                if ((this.VatField.Equals(value) != true)) {
                    this.VatField = value;
                    this.RaisePropertyChanged("Vat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="COMPTA_CustomerJournalLine", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class COMPTA_CustomerJournalLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> clientAccount_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> postingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> clientAccount_id {
            get {
                return this.clientAccount_idField;
            }
            set {
                if ((this.clientAccount_idField.Equals(value) != true)) {
                    this.clientAccount_idField = value;
                    this.RaisePropertyChanged("clientAccount_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> direction {
            get {
                return this.directionField;
            }
            set {
                if ((this.directionField.Equals(value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> postingDate {
            get {
                return this.postingDateField;
            }
            set {
                if ((this.postingDateField.Equals(value) != true)) {
                    this.postingDateField = value;
                    this.RaisePropertyChanged("postingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="COMPTA_SupplierJournalLine", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class COMPTA_SupplierJournalLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SupplierAccount_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> postingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SupplierAccount_id {
            get {
                return this.SupplierAccount_idField;
            }
            set {
                if ((this.SupplierAccount_idField.Equals(value) != true)) {
                    this.SupplierAccount_idField = value;
                    this.RaisePropertyChanged("SupplierAccount_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> direction {
            get {
                return this.directionField;
            }
            set {
                if ((this.directionField.Equals(value) != true)) {
                    this.directionField = value;
                    this.RaisePropertyChanged("direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> postingDate {
            get {
                return this.postingDateField;
            }
            set {
                if ((this.postingDateField.Equals(value) != true)) {
                    this.postingDateField = value;
                    this.RaisePropertyChanged("postingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company_Contact", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Company_Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long company_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long company_id {
            get {
                return this.company_idField;
            }
            set {
                if ((this.company_idField.Equals(value) != true)) {
                    this.company_idField = value;
                    this.RaisePropertyChanged("company_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_Transmitter", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_Transmitter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation[] BILL_BillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NSiretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Transmitter_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdressMail {
            get {
                return this.AdressMailField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressMailField, value) != true)) {
                    this.AdressMailField = value;
                    this.RaisePropertyChanged("AdressMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation[] BILL_BillQuotation {
            get {
                return this.BILL_BillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationField, value) != true)) {
                    this.BILL_BillQuotationField = value;
                    this.RaisePropertyChanged("BILL_BillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NSiret {
            get {
                return this.NSiretField;
            }
            set {
                if ((this.NSiretField.Equals(value) != true)) {
                    this.NSiretField = value;
                    this.RaisePropertyChanged("NSiret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((this.PostCodeField.Equals(value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Transmitter_Id {
            get {
                return this.Transmitter_IdField;
            }
            set {
                if ((this.Transmitter_IdField.Equals(value) != true)) {
                    this.Transmitter_IdField = value;
                    this.RaisePropertyChanged("Transmitter_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_BillQuotationStatus", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_BillQuotationStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation BILL_BillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillQuotationStatus_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BillQuotation_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateAdvancementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Status_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation BILL_BillQuotation {
            get {
                return this.BILL_BillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationField, value) != true)) {
                    this.BILL_BillQuotationField = value;
                    this.RaisePropertyChanged("BILL_BillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_Status {
            get {
                return this.BILL_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_StatusField, value) != true)) {
                    this.BILL_StatusField = value;
                    this.RaisePropertyChanged("BILL_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillQuotationStatus_Id {
            get {
                return this.BillQuotationStatus_IdField;
            }
            set {
                if ((this.BillQuotationStatus_IdField.Equals(value) != true)) {
                    this.BillQuotationStatus_IdField = value;
                    this.RaisePropertyChanged("BillQuotationStatus_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BillQuotation_Id {
            get {
                return this.BillQuotation_IdField;
            }
            set {
                if ((this.BillQuotation_IdField.Equals(value) != true)) {
                    this.BillQuotation_IdField = value;
                    this.RaisePropertyChanged("BillQuotation_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateAdvancement {
            get {
                return this.DateAdvancementField;
            }
            set {
                if ((this.DateAdvancementField.Equals(value) != true)) {
                    this.DateAdvancementField = value;
                    this.RaisePropertyChanged("DateAdvancement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_LineBillQuotation", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_LineBillQuotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation BILL_BillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Product BILL_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BillQuotation_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LineBillQuotation_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotation BILL_BillQuotation {
            get {
                return this.BILL_BillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationField, value) != true)) {
                    this.BILL_BillQuotationField = value;
                    this.RaisePropertyChanged("BILL_BillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Product BILL_Product {
            get {
                return this.BILL_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_ProductField, value) != true)) {
                    this.BILL_ProductField = value;
                    this.RaisePropertyChanged("BILL_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BillQuotation_Id {
            get {
                return this.BillQuotation_IdField;
            }
            set {
                if ((this.BillQuotation_IdField.Equals(value) != true)) {
                    this.BillQuotation_IdField = value;
                    this.RaisePropertyChanged("BillQuotation_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLine {
            get {
                return this.DateLineField;
            }
            set {
                if ((this.DateLineField.Equals(value) != true)) {
                    this.DateLineField = value;
                    this.RaisePropertyChanged("DateLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LineBillQuotation_Id {
            get {
                return this.LineBillQuotation_IdField;
            }
            set {
                if ((this.LineBillQuotation_IdField.Equals(value) != true)) {
                    this.LineBillQuotation_IdField = value;
                    this.RaisePropertyChanged("LineBillQuotation_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_Status", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotationStatus[] BILL_BillQuotationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_StatusChain[] BILL_StatusChainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_StatusChain[] BILL_StatusChain1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Status_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_BillQuotationStatus[] BILL_BillQuotationStatus {
            get {
                return this.BILL_BillQuotationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_BillQuotationStatusField, value) != true)) {
                    this.BILL_BillQuotationStatusField = value;
                    this.RaisePropertyChanged("BILL_BillQuotationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_StatusChain[] BILL_StatusChain {
            get {
                return this.BILL_StatusChainField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_StatusChainField, value) != true)) {
                    this.BILL_StatusChainField = value;
                    this.RaisePropertyChanged("BILL_StatusChain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_StatusChain[] BILL_StatusChain1 {
            get {
                return this.BILL_StatusChain1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_StatusChain1Field, value) != true)) {
                    this.BILL_StatusChain1Field = value;
                    this.RaisePropertyChanged("BILL_StatusChain1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libel {
            get {
                return this.LibelField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelField, value) != true)) {
                    this.LibelField = value;
                    this.RaisePropertyChanged("Libel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_StatusChain", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_StatusChain : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_Status1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> NextStatus_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long StatusChain_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Status_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_Status {
            get {
                return this.BILL_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_StatusField, value) != true)) {
                    this.BILL_StatusField = value;
                    this.RaisePropertyChanged("BILL_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Status BILL_Status1 {
            get {
                return this.BILL_Status1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_Status1Field, value) != true)) {
                    this.BILL_Status1Field = value;
                    this.RaisePropertyChanged("BILL_Status1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> NextStatus_Id {
            get {
                return this.NextStatus_IdField;
            }
            set {
                if ((this.NextStatus_IdField.Equals(value) != true)) {
                    this.NextStatus_IdField = value;
                    this.RaisePropertyChanged("NextStatus_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long StatusChain_Id {
            get {
                return this.StatusChain_IdField;
            }
            set {
                if ((this.StatusChain_IdField.Equals(value) != true)) {
                    this.StatusChain_IdField = value;
                    this.RaisePropertyChanged("StatusChain_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_Product", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Category BILL_CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_LineBillQuotation[] BILL_LineBillQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Vat BILL_VatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Category_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Product_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Vat_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Category BILL_Category {
            get {
                return this.BILL_CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_CategoryField, value) != true)) {
                    this.BILL_CategoryField = value;
                    this.RaisePropertyChanged("BILL_Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_LineBillQuotation[] BILL_LineBillQuotation {
            get {
                return this.BILL_LineBillQuotationField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_LineBillQuotationField, value) != true)) {
                    this.BILL_LineBillQuotationField = value;
                    this.RaisePropertyChanged("BILL_LineBillQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Vat BILL_Vat {
            get {
                return this.BILL_VatField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_VatField, value) != true)) {
                    this.BILL_VatField = value;
                    this.RaisePropertyChanged("BILL_Vat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Category_Id {
            get {
                return this.Category_IdField;
            }
            set {
                if ((this.Category_IdField.Equals(value) != true)) {
                    this.Category_IdField = value;
                    this.RaisePropertyChanged("Category_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionPro {
            get {
                return this.DescriptionProField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionProField, value) != true)) {
                    this.DescriptionProField = value;
                    this.RaisePropertyChanged("DescriptionPro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Product_Id {
            get {
                return this.Product_IdField;
            }
            set {
                if ((this.Product_IdField.Equals(value) != true)) {
                    this.Product_IdField = value;
                    this.RaisePropertyChanged("Product_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Vat_Id {
            get {
                return this.Vat_IdField;
            }
            set {
                if ((this.Vat_IdField.Equals(value) != true)) {
                    this.Vat_IdField = value;
                    this.RaisePropertyChanged("Vat_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_Category", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Product[] BILL_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Category_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionCatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Product[] BILL_Product {
            get {
                return this.BILL_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_ProductField, value) != true)) {
                    this.BILL_ProductField = value;
                    this.RaisePropertyChanged("BILL_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Category_Id {
            get {
                return this.Category_IdField;
            }
            set {
                if ((this.Category_IdField.Equals(value) != true)) {
                    this.Category_IdField = value;
                    this.RaisePropertyChanged("Category_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionCat {
            get {
                return this.DescriptionCatField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionCatField, value) != true)) {
                    this.DescriptionCatField = value;
                    this.RaisePropertyChanged("DescriptionCat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BILL_Vat", Namespace="http://schemas.datacontract.org/2004/07/SupErp.Entities", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BILL_Vat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UserControl_GestionClient.ClientServiceGestionClient.BILL_Product[] BILL_ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateVatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Vat_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserControl_GestionClient.ClientServiceGestionClient.BILL_Product[] BILL_Product {
            get {
                return this.BILL_ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_ProductField, value) != true)) {
                    this.BILL_ProductField = value;
                    this.RaisePropertyChanged("BILL_Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateVat {
            get {
                return this.DateVatField;
            }
            set {
                if ((this.DateVatField.Equals(value) != true)) {
                    this.DateVatField = value;
                    this.RaisePropertyChanged("DateVat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Vat_Id {
            get {
                return this.Vat_IdField;
            }
            set {
                if ((this.Vat_IdField.Equals(value) != true)) {
                    this.Vat_IdField = value;
                    this.RaisePropertyChanged("Vat_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceGestionClient.IServiceGestionClient")]
    public interface IServiceGestionClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/CreateCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/CreateCompanyResponse")]
        int CreateCompany(UserControl_GestionClient.ClientServiceGestionClient.Company company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/CreateCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/CreateCompanyResponse")]
        System.Threading.Tasks.Task<int> CreateCompanyAsync(UserControl_GestionClient.ClientServiceGestionClient.Company company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/GetCompanyResponse")]
        UserControl_GestionClient.ClientServiceGestionClient.Company GetCompany(int idCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/GetCompanyResponse")]
        System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company> GetCompanyAsync(int idCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompanyResponse")]
        UserControl_GestionClient.ClientServiceGestionClient.Company[] GetListCompany();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompanyResponse")]
        System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company[]> GetListCompanyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/EditCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/EditCompanyResponse")]
        bool EditCompany(UserControl_GestionClient.ClientServiceGestionClient.Company company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/EditCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/EditCompanyResponse")]
        System.Threading.Tasks.Task<bool> EditCompanyAsync(UserControl_GestionClient.ClientServiceGestionClient.Company company);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/DeleteCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/DeleteCompanyResponse")]
        bool DeleteCompany(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/DeleteCompany", ReplyAction="http://tempuri.org/IServiceGestionClient/DeleteCompanyResponse")]
        System.Threading.Tasks.Task<bool> DeleteCompanyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/CreateCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/CreateCompany_ContactResponse")]
        int CreateCompany_Contact(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/CreateCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/CreateCompany_ContactResponse")]
        System.Threading.Tasks.Task<int> CreateCompany_ContactAsync(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/GetCompany_ContactResponse")]
        UserControl_GestionClient.ClientServiceGestionClient.Company_Contact GetCompany_Contact(int idContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/GetCompany_ContactResponse")]
        System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact> GetCompany_ContactAsync(int idContact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactResponse")]
        UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] GetListCompany_Contact();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactResponse")]
        System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[]> GetListCompany_ContactAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactById", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactByIdResponse")]
        UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] GetListCompany_ContactById(int idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactById", ReplyAction="http://tempuri.org/IServiceGestionClient/GetListCompany_ContactByIdResponse")]
        System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[]> GetListCompany_ContactByIdAsync(int idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/EditCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/EditCompany_ContactResponse")]
        bool EditCompany_Contact(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/EditCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/EditCompany_ContactResponse")]
        System.Threading.Tasks.Task<bool> EditCompany_ContactAsync(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/DeleteCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/DeleteCompany_ContactResponse")]
        bool DeleteCompany_Contact(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGestionClient/DeleteCompany_Contact", ReplyAction="http://tempuri.org/IServiceGestionClient/DeleteCompany_ContactResponse")]
        System.Threading.Tasks.Task<bool> DeleteCompany_ContactAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceGestionClientChannel : UserControl_GestionClient.ClientServiceGestionClient.IServiceGestionClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGestionClientClient : System.ServiceModel.ClientBase<UserControl_GestionClient.ClientServiceGestionClient.IServiceGestionClient>, UserControl_GestionClient.ClientServiceGestionClient.IServiceGestionClient {
        
        public ServiceGestionClientClient() {
        }
        
        public ServiceGestionClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGestionClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGestionClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGestionClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateCompany(UserControl_GestionClient.ClientServiceGestionClient.Company company) {
            return base.Channel.CreateCompany(company);
        }
        
        public System.Threading.Tasks.Task<int> CreateCompanyAsync(UserControl_GestionClient.ClientServiceGestionClient.Company company) {
            return base.Channel.CreateCompanyAsync(company);
        }
        
        public UserControl_GestionClient.ClientServiceGestionClient.Company GetCompany(int idCustomer) {
            return base.Channel.GetCompany(idCustomer);
        }
        
        public System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company> GetCompanyAsync(int idCustomer) {
            return base.Channel.GetCompanyAsync(idCustomer);
        }
        
        public UserControl_GestionClient.ClientServiceGestionClient.Company[] GetListCompany() {
            return base.Channel.GetListCompany();
        }
        
        public System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company[]> GetListCompanyAsync() {
            return base.Channel.GetListCompanyAsync();
        }
        
        public bool EditCompany(UserControl_GestionClient.ClientServiceGestionClient.Company company) {
            return base.Channel.EditCompany(company);
        }
        
        public System.Threading.Tasks.Task<bool> EditCompanyAsync(UserControl_GestionClient.ClientServiceGestionClient.Company company) {
            return base.Channel.EditCompanyAsync(company);
        }
        
        public bool DeleteCompany(int id) {
            return base.Channel.DeleteCompany(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCompanyAsync(int id) {
            return base.Channel.DeleteCompanyAsync(id);
        }
        
        public int CreateCompany_Contact(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact) {
            return base.Channel.CreateCompany_Contact(contact);
        }
        
        public System.Threading.Tasks.Task<int> CreateCompany_ContactAsync(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact) {
            return base.Channel.CreateCompany_ContactAsync(contact);
        }
        
        public UserControl_GestionClient.ClientServiceGestionClient.Company_Contact GetCompany_Contact(int idContact) {
            return base.Channel.GetCompany_Contact(idContact);
        }
        
        public System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact> GetCompany_ContactAsync(int idContact) {
            return base.Channel.GetCompany_ContactAsync(idContact);
        }
        
        public UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] GetListCompany_Contact() {
            return base.Channel.GetListCompany_Contact();
        }
        
        public System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[]> GetListCompany_ContactAsync() {
            return base.Channel.GetListCompany_ContactAsync();
        }
        
        public UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[] GetListCompany_ContactById(int idCompany) {
            return base.Channel.GetListCompany_ContactById(idCompany);
        }
        
        public System.Threading.Tasks.Task<UserControl_GestionClient.ClientServiceGestionClient.Company_Contact[]> GetListCompany_ContactByIdAsync(int idCompany) {
            return base.Channel.GetListCompany_ContactByIdAsync(idCompany);
        }
        
        public bool EditCompany_Contact(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact) {
            return base.Channel.EditCompany_Contact(contact);
        }
        
        public System.Threading.Tasks.Task<bool> EditCompany_ContactAsync(UserControl_GestionClient.ClientServiceGestionClient.Company_Contact contact) {
            return base.Channel.EditCompany_ContactAsync(contact);
        }
        
        public bool DeleteCompany_Contact(int id) {
            return base.Channel.DeleteCompany_Contact(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCompany_ContactAsync(int id) {
            return base.Channel.DeleteCompany_ContactAsync(id);
        }
    }
}
