//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Absence))]
    [KnownType(typeof(ConfigAbsence))]
    
    public partial class AbsenceType
    {
        public AbsenceType()
        {
            this.Absences = new HashSet<Absence>();
            this.ConfigAbsences = new HashSet<ConfigAbsence>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string Label { get; set; }
    
    [DataMember]
        public virtual ICollection<Absence> Absences { get; set; }
    [DataMember]
        public virtual ICollection<ConfigAbsence> ConfigAbsences { get; set; }
    }
}
