//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_BillQuotationStatus
    {
        public long BillQuotationStatus_Id { get; set; }
        public System.DateTime DateAdvancement { get; set; }
        public long Status_Id { get; set; }
        public long BillQuotation_Id { get; set; }
    
        public virtual BILL_BillQuotation BILL_BillQuotation { get; set; }
        public virtual BILL_Status BILL_Status { get; set; }
    }
}
