//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotation))]
    
    public partial class BILL_Transmitter
    {
        public BILL_Transmitter()
        {
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
        }
    
    [DataMember]
        public long Transmitter_Id { get; set; }
    [DataMember]
        public string CompanyName { get; set; }
    [DataMember]
        public string Adress { get; set; }
    [DataMember]
        public Nullable<int> PostCode { get; set; }
    [DataMember]
        public string City { get; set; }
    [DataMember]
        public long NSiret { get; set; }
    [DataMember]
        public string AdressMail { get; set; }
    [DataMember]
        public string Phone { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    }
}
