//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotationStatus))]
    [KnownType(typeof(BILL_Transmitter))]
    [KnownType(typeof(BILL_LineBillQuotation))]
    [KnownType(typeof(Company))]
    
    public partial class BILL_BillQuotation
    {
        public BILL_BillQuotation()
        {
            this.BILL_BillQuotationStatus = new HashSet<BILL_BillQuotationStatus>();
            this.BILL_LineBillQuotation = new HashSet<BILL_LineBillQuotation>();
        }
    
    [DataMember]
        public long BillQuotation_Id { get; set; }
    [DataMember]
        public string NBill { get; set; }
    [DataMember]
        public Nullable<bool> Vat { get; set; }
    [DataMember]
        public int AmountDF { get; set; }
    [DataMember]
        public System.DateTime DateBillQuotation { get; set; }
    [DataMember]
        public Nullable<long> Transmitter_Id { get; set; }
    [DataMember]
        public Nullable<long> Company_Id { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_BillQuotationStatus> BILL_BillQuotationStatus { get; set; }
    [DataMember]
        public virtual BILL_Transmitter BILL_Transmitter { get; set; }
    [DataMember]
        public virtual ICollection<BILL_LineBillQuotation> BILL_LineBillQuotation { get; set; }
    [DataMember]
        public virtual Company Company { get; set; }
    }
}
