//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_Vat
    {
        public BILL_Vat()
        {
            this.BILL_Product = new HashSet<BILL_Product>();
        }
    
        public long Vat_Id { get; set; }
        public Nullable<double> Rate { get; set; }
        public System.DateTime DateVat { get; set; }
    
        public virtual ICollection<BILL_Product> BILL_Product { get; set; }
    }
}
