//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_BillQuotation
    {
        public BILL_BillQuotation()
        {
            this.BILL_BillQuotationStatus = new HashSet<BILL_BillQuotationStatus>();
            this.BILL_LineBillQuotation = new HashSet<BILL_LineBillQuotation>();
        }
    
        public long BillQuotation_Id { get; set; }
        public string NBill { get; set; }
        public Nullable<bool> Vat { get; set; }
        public int AmountDF { get; set; }
        public System.DateTime DateBillQuotation { get; set; }
        public Nullable<long> Customer_Id { get; set; }
        public Nullable<long> Transmitter_Id { get; set; }
        public Nullable<long> Company_Id { get; set; }
    
        public virtual ICollection<BILL_BillQuotationStatus> BILL_BillQuotationStatus { get; set; }
        public virtual BILL_Transmitter BILL_Transmitter { get; set; }
        public virtual ICollection<BILL_LineBillQuotation> BILL_LineBillQuotation { get; set; }
        public virtual Company Company { get; set; }
    }
}
