//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_Category))]
    [KnownType(typeof(BILL_LineBillQuotation))]
    [KnownType(typeof(BILL_Vat))]
    
    public partial class BILL_Product
    {
        public BILL_Product()
        {
            this.BILL_LineBillQuotation = new HashSet<BILL_LineBillQuotation>();
        }
    
    [DataMember]
        public long Product_Id { get; set; }
    [DataMember]
        public string Name { get; set; }
    [DataMember]
        public string DescriptionPro { get; set; }
    [DataMember]
        public double Price { get; set; }
        public long Category_Id { get; set; }
        public long Vat_Id { get; set; }
    
    [DataMember]
        public virtual BILL_Category BILL_Category { get; set; }
    [DataMember]
        public virtual ICollection<BILL_LineBillQuotation> BILL_LineBillQuotation { get; set; }
    [DataMember]
        public virtual BILL_Vat BILL_Vat { get; set; }
    }
}
