//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotation))]
    [KnownType(typeof(BILL_Product))]
    
    public partial class BILL_LineBillQuotation
    {
    [DataMember]
        public long LineBillQuotation_Id { get; set; }
    [DataMember]
        public System.DateTime DateLine { get; set; }
    [DataMember]
        public double Quantite { get; set; }
    [DataMember]
        public Nullable<long> BillQuotation_Id { get; set; }
    [DataMember]
        public Nullable<long> Product_Id { get; set; }
    
    [DataMember]
        public virtual BILL_BillQuotation BILL_BillQuotation { get; set; }
    [DataMember]
        public virtual BILL_Product BILL_Product { get; set; }
    }
}
