//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotation))]
    [KnownType(typeof(BILL_Status))]
    
    public partial class BILL_BillQuotationStatus
    {
    [DataMember]
        public long BillQuotationStatus_Id { get; set; }
    [DataMember]
        public System.DateTime DateAdvancement { get; set; }
        public long Status_Id { get; set; }
        public long BillQuotation_Id { get; set; }
    
    [DataMember]
        public virtual BILL_BillQuotation BILL_BillQuotation { get; set; }
    [DataMember]
        public virtual BILL_Status BILL_Status { get; set; }
    }
}
