//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_Product))]
    
    public partial class BILL_Vat
    {
        public BILL_Vat()
        {
            this.BILL_Product = new HashSet<BILL_Product>();
        }
    
    [DataMember]
        public long Vat_Id { get; set; }
    [DataMember]
        public Nullable<double> Rate { get; set; }
    [DataMember]
        public System.DateTime DateVat { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_Product> BILL_Product { get; set; }
    }
}
