//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotationStatus))]
    [KnownType(typeof(BILL_Transmitter))]
    [KnownType(typeof(BILL_LineBillQuotation))]
    [KnownType(typeof(Company))]
    
    public partial class BILL_BillQuotation
    {
        public BILL_BillQuotation()
        {
            this.BILL_BillQuotationStatus = new HashSet<BILL_BillQuotationStatus>();
            this.BILL_LineBillQuotation = new HashSet<BILL_LineBillQuotation>();
        }
    
    [DataMember]
        public long BillQuotation_Id { get; set; }
    [DataMember]
        public string NBill { get; set; }
    [DataMember]
        public bool Vat { get; set; }
    [DataMember]
        public double AmountDF { get; set; }
    [DataMember]
        public System.DateTime DateBillQuotation { get; set; }
    [DataMember]
        public long Transmitter_Id { get; set; }
    [DataMember]
        public long Company_Id { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_BillQuotationStatus> BILL_BillQuotationStatus { get; set; }
    [DataMember]
        public virtual BILL_Transmitter BILL_Transmitter { get; set; }
    [DataMember]
        public virtual ICollection<BILL_LineBillQuotation> BILL_LineBillQuotation { get; set; }
    [DataMember]
        public virtual Company Company { get; set; }
    }
}
