//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_Category))]
    [KnownType(typeof(BILL_LineBillQuotation))]
    [KnownType(typeof(BILL_Vat))]
    
    public partial class BILL_Product
    {
        public BILL_Product()
        {
            this.BILL_LineBillQuotation = new HashSet<BILL_LineBillQuotation>();
        }
    
    [DataMember]
        public long Product_Id { get; set; }
    [DataMember]
        public string Name { get; set; }
    [DataMember]
        public string DescriptionPro { get; set; }
    [DataMember]
        public double Price { get; set; }
    [DataMember]
        public long Category_Id { get; set; }
    [DataMember]
        public long Vat_Id { get; set; }
    
    [DataMember]
        public virtual BILL_Category BILL_Category { get; set; }
    [DataMember]
        public virtual ICollection<BILL_LineBillQuotation> BILL_LineBillQuotation { get; set; }
    [DataMember]
        public virtual BILL_Vat BILL_Vat { get; set; }
    }
}
