//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotation))]
    
    public partial class BILL_Transmitter
    {
        public BILL_Transmitter()
        {
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
        }
    
    [DataMember]
        public long Transmitter_Id { get; set; }
    [DataMember]
        public string CompanyName { get; set; }
    [DataMember]
        public string Adress { get; set; }
    [DataMember]
        public Nullable<int> PostCode { get; set; }
    [DataMember]
        public string City { get; set; }
    [DataMember]
        public long NSiret { get; set; }
    [DataMember]
        public string AdressMail { get; set; }
    [DataMember]
        public string Phone { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    }
}
