//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BILL_BillQuotation))]
    [KnownType(typeof(Company_Contact))]
    
    public partial class Company
    {
        public Company()
        {
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
            this.Company_Contact = new HashSet<Company_Contact>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public string siret { get; set; }
    [DataMember]
        public string address { get; set; }
    [DataMember]
        public int postalcode { get; set; }
    [DataMember]
        public string city { get; set; }
    
    [DataMember]
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    [DataMember]
        public virtual ICollection<Company_Contact> Company_Contact { get; set; }
    }
}
