//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPTA_AccountingEntries))]
    [KnownType(typeof(COMPTA_Periodicity))]
    
    public partial class COMPTA_AccountingEntries_Periodicity
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<System.DateTime> startDate { get; set; }
    [DataMember]
        public Nullable<System.DateTime> endDate { get; set; }
    [DataMember]
        public Nullable<long> accountingEntries_id { get; set; }
    [DataMember]
        public Nullable<long> periodicity_id { get; set; }
    
    [DataMember]
        public virtual COMPTA_AccountingEntries COMPTA_AccountingEntries { get; set; }
    [DataMember]
        public virtual COMPTA_Periodicity COMPTA_Periodicity { get; set; }
    }
}
