//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPTA_AccountingEntries
    {
        public long id { get; set; }
        public Nullable<bool> direction { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> postingDate { get; set; }
        public Nullable<long> chartOfAccount_id { get; set; }
    }
}
