//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Company_Contact))]
    [KnownType(typeof(BILL_BillQuotation))]
    [KnownType(typeof(COMPTA_CustomerJournalLine))]
    [KnownType(typeof(COMPTA_SupplierJournalLine))]
    
    public partial class Company
    {
        public Company()
        {
            this.Company_Contact = new HashSet<Company_Contact>();
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
            this.COMPTA_CustomerJournalLine = new HashSet<COMPTA_CustomerJournalLine>();
            this.COMPTA_SupplierJournalLine = new HashSet<COMPTA_SupplierJournalLine>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public string siret { get; set; }
    [DataMember]
        public string address { get; set; }
    [DataMember]
        public int postalcode { get; set; }
    [DataMember]
        public string city { get; set; }
    
    [DataMember]
        public virtual ICollection<Company_Contact> Company_Contact { get; set; }
    [DataMember]
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    [DataMember]
        public virtual ICollection<COMPTA_CustomerJournalLine> COMPTA_CustomerJournalLine { get; set; }
    [DataMember]
        public virtual ICollection<COMPTA_SupplierJournalLine> COMPTA_SupplierJournalLine { get; set; }
    }
}
