//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPTA_BankAccount))]
    
    public partial class COMPTA_Currency
    {
        public COMPTA_Currency()
        {
            this.COMPTA_BankAccount = new HashSet<COMPTA_BankAccount>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public string symbol { get; set; }
    
    [DataMember]
        public virtual ICollection<COMPTA_BankAccount> COMPTA_BankAccount { get; set; }
    }
}
