//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPTA_Bank))]
    [KnownType(typeof(COMPTA_BankJournalLine))]
    [KnownType(typeof(COMPTA_Currency))]
    
    public partial class COMPTA_BankAccount
    {
        public COMPTA_BankAccount()
        {
            this.COMPTA_BankJournalLine = new HashSet<COMPTA_BankJournalLine>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string fullName { get; set; }
    [DataMember]
        public string shortName { get; set; }
    [DataMember]
        public string swiftCode { get; set; }
    [DataMember]
        public string IBAN { get; set; }
    [DataMember]
        public string ABA { get; set; }
    [DataMember]
        public string accountNumber { get; set; }
    [DataMember]
        public string RIB { get; set; }
    [DataMember]
        public string keyRIB { get; set; }
    [DataMember]
        public Nullable<long> currency_id { get; set; }
    [DataMember]
        public Nullable<long> bank_id { get; set; }
    
    [DataMember]
        public virtual COMPTA_Bank COMPTA_Bank { get; set; }
    [DataMember]
        public virtual ICollection<COMPTA_BankJournalLine> COMPTA_BankJournalLine { get; set; }
    [DataMember]
        public virtual COMPTA_Currency COMPTA_Currency { get; set; }
    }
}
