//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPTA_AccountingEntries))]
    [KnownType(typeof(COMPTA_ClassOfAccounts))]
    
    public partial class COMPTA_ChartOfAccounts
    {
        public COMPTA_ChartOfAccounts()
        {
            this.COMPTA_AccountingEntries = new HashSet<COMPTA_AccountingEntries>();
        }
    
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<long> account_number { get; set; }
    [DataMember]
        public string name { get; set; }
    [DataMember]
        public Nullable<long> class_id { get; set; }
    
    [DataMember]
        public virtual ICollection<COMPTA_AccountingEntries> COMPTA_AccountingEntries { get; set; }
    [DataMember]
        public virtual COMPTA_ClassOfAccounts COMPTA_ClassOfAccounts { get; set; }
    }
}
