//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(COMPTA_BankAccount))]
    
    public partial class COMPTA_BankJournalLine
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<bool> direction { get; set; }
    [DataMember]
        public Nullable<decimal> amount { get; set; }
    [DataMember]
        public Nullable<System.DateTime> postingDate { get; set; }
    [DataMember]
        public Nullable<long> bankAccount_id { get; set; }
    
    [DataMember]
        public virtual COMPTA_BankAccount COMPTA_BankAccount { get; set; }
    }
}
