//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Company))]
    
    public partial class Company_Contact
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public string firstname { get; set; }
    [DataMember]
        public string lastname { get; set; }
    [DataMember]
        public int gender { get; set; }
    [DataMember]
        public string email { get; set; }
    [DataMember]
        public string phone { get; set; }
    [DataMember]
        public long company_id { get; set; }
    
    [DataMember]
        public virtual Company Company { get; set; }
    }
}
