//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(AbsenceType))]
    
    public partial class ConfigAbsence
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<int> MaximumHalfDayAbsence { get; set; }
    [DataMember]
        public Nullable<long> AbsenceType_id { get; set; }
    
    [DataMember]
        public virtual AbsenceType AbsenceType { get; set; }
    }
}
