//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(AbsenceType))]
    
    public partial class ConfigAbsence
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<int> MaximumHalfDayAbsence { get; set; }
    [DataMember]
        public Nullable<long> AbsenceType_id { get; set; }
    
    [DataMember]
        public virtual AbsenceType AbsenceType { get; set; }
    }
}
