//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BILL_BillQuotation = new HashSet<BILL_BillQuotation>();
        }
    
        public long id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int gender { get; set; }
        public string company { get; set; }
        public string siret { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public int postalcode { get; set; }
        public string city { get; set; }
    
        public virtual ICollection<BILL_BillQuotation> BILL_BillQuotation { get; set; }
    }
}
