//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(RoleModule))]
    
    public partial class Module
    {
        public Module()
        {
            this.RoleModules = new HashSet<RoleModule>();
        }
    
    [DataMember]
        public long Id { get; set; }
    [DataMember]
        public string Name { get; set; }
    
    [DataMember]
        public virtual ICollection<RoleModule> RoleModules { get; set; }
    }
}
