//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(User))]
    
    public partial class Prime
    {
    [DataMember]
        public long id { get; set; }
    [DataMember]
        public Nullable<long> User_id { get; set; }
    [DataMember]
        public string Label { get; set; }
    [DataMember]
        public Nullable<System.DateTime> StartDate { get; set; }
    [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
    [DataMember]
        public Nullable<decimal> Price { get; set; }
    
    [DataMember]
        public virtual User User { get; set; }
    }
}
