//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupErp.Entities
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Module))]
    [KnownType(typeof(Role))]
    
    public partial class RoleModule
    {
    [DataMember]
        public long Id { get; set; }
    [DataMember]
        public long Module_id { get; set; }
    [DataMember]
        public long Role_id { get; set; }
    
    [DataMember]
        public virtual Module Module { get; set; }
    [DataMember]
        public virtual Role Role { get; set; }
    }
}
