//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryLibrary.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SUPERPDEVEntities : DbContext
    {
        public SUPERPDEVEntities()
            : base("name=SUPERPDEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<AbsenceType> AbsenceTypes { get; set; }
        public virtual DbSet<ConfigAbsence> ConfigAbsences { get; set; }
        public virtual DbSet<Prime> Primes { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TicketRestaurant> TicketRestaurants { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
