//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Users = new HashSet<User>();
        }
    
        public long id { get; set; }
        public string Label { get; set; }
        public Nullable<decimal> PercentageTaxe { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
